package org.tillerino.jagger.annotations;

/**
 * Marks code generated by Jagger. By default, this is added to generated classes. Turn off with
 * {@link JsonConfig#addGeneratedAnnotationToClass()}. Optionally, this can be added to generated methods and
 * constructors, see {@link JsonConfig#addGeneratedAnnotationToMethods()}.
 */
public @interface Generated {}
